### ISSUE TITLE
[FEAT] 앨범이름으로 검색

### ISSUE THREAD

**Issue by kchaeys2** [Mu-necting/Mu-necting_Server#16]
## 📋 설명
spotify api 사용하고 track으로 호출하는 기능
검색은 앨범 이름으로만 가능

## ✅ TO-DO
- [x] 앨범 이름-spotify
- [x] 앨범 사진-spotify
- [x] 가수 이름 - spotify
- [ ] #19
- [x] #20
- [x] #46 
- [x] #48
- [x] #18
