### ISSUE TITLE
[FEAT] entity 구현

### ISSUE THREAD

**Issue by kchaeys2** [Mu-necting/Mu-necting_Server#3]
### 📋 설명
~~1차 엔터티 구현~~
~~기획 변경 및 1차 엔터티 구조 오류로 인해 엔터티 수정 필요~~
랭킹 조회와 pick 개수 상시 조회가 많아 관련 컬럼 추가

### ✅ TO-DO
- [x] pick 테이블 생성
- [x] hashTag 테이블 삭제
- [x] genre 테이블 삭제
- [x] music과 achive 테이블 관계 재설정
- [x] 멤버 entity intro 삭제
- [x] 멤버 phone 삭제, 푸시 알림 삭제
- [x] 멤버 카카오 로그인 토큰만 받고 유저 정보 전달
- [x] 멤버 all_reply cnt 추가
- [x] 아카이브 ach_pick cnt 추가

### 🎵 ETC
